### PR TITLE
Add HTTP2 support to server

### PR DESCRIPTION
**Pull request by bengadbois**
I'm not sure if this is the best way to do it, basically just switched out the express server. It loads everything (html, js, all the assets) as http2.

Page loads don't _feel_ any faster, but the header compression and http2 server push is happening, so it should be slightly faster on slow connections.

### CODE REVIEW

**Comment by jfurrow** [comment]
Thanks for the PR!

Let's make this configurable by adding an option in `config.template.js` (something like `useHTTP2`). Then we can default to `https` but use `spdy` if the configuration is present.

**Comment by bengadbois** [comment]
@jfurrow is there any reason someone would use `https` over `spdy`? The `spdy` module will gracefully fallback to HTTPS 1.1 in the cases that HTTP/2 or SPDY isn't supported by a browser (or something proxying in front).

**Comment by jfurrow** [comment]
@bengadbois Oh cool, I didn't know that. I honestly don't know much about HTTP2 or SPDY.

Anyway, the package seems well supported, but this isn't working for me... the server just never responds. Do I need to generate the certificate in a special way?

**Comment by bengadbois** [comment]
I didn't need to, just an npm install and flood restart. So the flood server never responds to any HTTPS requests then (HTTP/2 only works with HTTPS)? Are you hitting it directly or proxying with something?

For me the same cert file, same port, nothing changed `config.json`, all worked the first time.

**Comment by jfurrow** [comment]
Alright, yeah I tried this again and it's working as expected, I'm not sure what happened earlier but let's ship it 🚢 ! Thanks for the PR

**Pull request merged**
