### PR TITLE
Logout functionality

### PR DESCRIPTION
**Pull request by chapm250**

### CODE REVIEW

**Comment by noraj1337** [comment]
That will close PR #446

**Comment by jfurrow** [comment]
@chapm250 I'm afraid this isn't working for me. When I click the icon, it redirects me to the login screen, but if I refresh the UI, I'm already authenticated and the UI loads as if I hadn't logged out.

**Comment by jfurrow** [comment]
@chapm250 Sorry but I'm going to close this in favor of https://github.com/jfurrow/flood/pull/539. I'll create the icon this weekend which will complete the PR.

**Comment by chapm250** [comment]
I am confused, why did you say in #539 that it just needs an icon if it is not working?

**Comment by jfurrow** [comment]
@chapm250 the logic you wrote in this PR is not working. The logic I wrote in PR #539 is working, but it still needs an icon, and I don't have time right now to create the icon.

**Comment by chapm250** [comment]
Ohh I didn't catch the server code difference. Worked for me, but either way your solution looks cleaner.

**Comment by jfurrow** [comment]
Ahh sorry for the confusion.

Also sorry if I closed a PR that was working as intended. Maybe I didn't pull your branch properly...

**Comment by chapm250** [comment]
It's all good. res.clearCookie looks like the more official way anyways, I'm glad I learned about it.

**Pull request closed without merging**
