### PR TITLE
[WIP] Create LogoutButton.js

### PR DESCRIPTION
**Pull request by noraj1337**

### CODE REVIEW

**Comment by jfurrow** [comment]
Hi @noraj1337, thanks for the PR. The code looks good so far! Is there anything you're stuck with?

**Comment by noraj1337** [comment]
@jfurrow Yeah, I don't know your code structure and how it really work so I don't know how to go farther. And JS is a lang I'm mastering :/

**Comment by jfurrow** [comment]
@noraj1337 That's totally understandable. Thanks for getting this started!

**Comment by jfurrow** [comment]
Closing this in favor of https://github.com/jfurrow/flood/pull/539

**Pull request closed without merging**
