### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by bbashy**
`npm install feedsub@0.6.0` was run.

## Description
Updated FeedSub to 0.6.0 as they pushed an update to the request library so that it follows 

## Related Issue
#679 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by noraj** [comment]
@bbashy you should join the discord server ;)

**Comment by bbashy** [comment]
@noraj Already on it?

**Comment by noraj** [comment]
I don't see some `bbashy` here.

**Comment by bbashy** [comment]
Just one b: bashy

**Pull request merged**
