### PR TITLE
Implement flood-ui-kit

### PR DESCRIPTION
**Pull request by jfurrow**
This basically replaces all of the form elements with those in [flood-ui-kit](https://github.com/jfurrow/flood-ui-kit). Along the way I made some minor design adjustments and cleaned up the codebase a bit.

If anyone's trying to follow along, sorry for the giant PR!

### CODE REVIEW

**Comment by jfurrow** [comment]
😬 Alright, let's do this.

**Comment by dcousens** [comment]
The [slight] `background-color` changes for modals look a little bit... less polished?
But the tags being lighter helps in readability.

<3 the hover effects for list items.

**Comment by dcousens** [comment]
tone
@jfurrow each Modal panel is now 1 color,  not 2 like in this

What is is now:

**Comment by jfurrow** [comment]
@dcousens The single-tone modal is intentional. They could use a more significant redesign (e.g remove the need for these large modals entirely), but I think this is an improvement.

**Comment by dcousens** [comment]
@jfurrow you could replace the throttles with a "custom" menu item in the throttle drop down,  which opens a pure-text modal with a "save" to enter the above data.

**Comment by dcousens** [comment]
Is the slot information *ever* changed in a live manner?

**Pull request merged**
