### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by noraj**
## Description

add `.github/stale.yml` for the. stale bot

## Related Issue

see https://github.com/jfurrow/flood/issues/628

## Motivation and Context

see https://github.com/jfurrow/flood/issues/628

## How Has This Been Tested?

N.A.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by noraj1337** [comment]
as said in see https://github.com/jfurrow/flood/issues/628, the bot need to be installed from here first https://github.com/apps/stale

**Comment by jfurrow** [comment]
I really don't see the value here, can you try to convince me @noraj1337?

Even though issues get old and stale, the preservation of the discussion is is useful. Flood development is moving really slowly (unfortunately), which would mean a lot of these issues would be closed without being resolved.

**Comment by noraj1337** [comment]
Here is how it works : `daysUntilStale` : time before being flagged as stale and then `daysUntilClose` time until it's closed since it entered into stale state.

As dev is slow we can increase the values, for example `daysUntilStale:120` (4 months) and `daysUntilClose:45`.

The goal is not to close the issue, in fact when an issue will be inactive for more than 4 months the bot will flag it as stale and put a message, so all people who are following this issue will get notified by github. These people will be able to say if they have more information about the issue, if they have a patch, an idea etc... or if the issue was solved by another one or is not happening anymore etc ... Then people can remove the stale flag or close the issue. There is only when nobody will care even after having been notified that the bot will close the issue (that's rare, for example when someone requesting a feature is not using the software anymore and that nobody else care).

So this is not for closing issues, but to get sure the issue is not forgotten, and to relaunch the debate.

So normally this will not hurt the preservation of issues but dynamism galvanize them.

@jfurrow What do you think? Are you convinced? :smile:

**Comment by jfurrow** [comment]
I'm gonna pass on this for now.

**Pull request closed without merging**
