### PR TITLE
Added columns for information on peer encryption and client to peer list

### PR DESCRIPTION
**Pull request by x-jojo**
I added some info columns to the peer list view:

- peer download percentage
- encryption status
- client info

flood
(I removed ip adresses in the screenshot)

### CODE REVIEW

**Comment by noraj1337** [comment]
I think it's a great idea.

**Comment by jfurrow** [comment]
Thanks @x-jojo!

Next time please check for linting errors (I should test for this in CI). I'll accept into a feature branch and fix up from there.

**Comment by schudt** [comment]
sorry, did it with plain vim on my server, next time I will ;)

**Comment by x-jojo** [comment]
> Next time please check for linting errors (I should test for this in CI). I'll accept into a feature branch and fix up from there.

sorry, did it with plain vim on my server, next time I will ;)

**Pull request merged**
