### PR TITLE
readme: add node-gyp and nodenv

### PR DESCRIPTION
**Pull request by noraj**
The readme is missing one step about node-gyp

### CODE REVIEW

**Comment by noraj** [comment]
This is why people are having this kind of error:

```
$ npm i

> argon2@0.19.3 install /srv/flood/node_modules/argon2
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:597:12)
gyp ERR! System Linux 4.19.26-1-lts
gyp ERR! command "/home/flood/.nodenv/versions/10.15.3/bin/node" "/home/flood/.nodenv/versions/10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                 
gyp ERR! cwd /srv/flood/node_modules/argon2
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})                                                                            

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flood/.npm/_logs/2019-03-06T21_47_23_738Z-debug.log
```

For example because they don't have python2.

**Comment by jfurrow** [comment]
This is not a requirement for all environments, why should we add to readme?

**Comment by noraj** [comment]
@jfurrow `node-gyp` is required for argon2. So node-gyp dependencies are required. So we need to tell people to install them. What's wrong in the sentence?:

> 3. Install `node-gyp` pre-requisites, see https://www.npmjs.com/package/node-gyp#installation, ex: `python2`, `make`, `gcc`.

Maybe you prefer:

> 3. Install `node-gyp` pre-requisites, see https://www.npmjs.com/package/node-gyp#installation (dependencies vary depending on the operating system)

**Comment by jfurrow** [comment]
@noraj You're right, sorry I was mistaken.

**Pull request merged**
