### PR TITLE
no active dev warning

### PR DESCRIPTION
**Pull request by noraj**
no active develoment warning in the readme

### CODE REVIEW

**Comment by jfurrow** [comment]
... I'm not gonna merge this

**Comment by noraj** [comment]
You have no time for this project anymore, we need new developers.

**Comment by jfurrow** [comment]
Perhaps a request for more developers would be more appropriate?

**Comment by GottZ** [comment]
¯\_(ツ)_/¯

disclaimer:
"dunno.. just blabbing here from my onscreen phone keyboard but there might be some truth to my comment. don't take this too serious"

i literally don't use flood anymore because of the open issues and rss improvements still not being merged.

i could probably hop onto the dev train but honestly.. this project is not too obviously structured from the viewpoint of a non-react dev and i don't intend to put my current projects aside just to help here.

yes, pulls can always be improved but it's usually a bad assumption to think potential contributors code the same style as the owner.
alot of interesting pulls die out in oss projects because rather than cherrypicking changes into a branch and letting a top contributor fix the pulls, they usually receive a big wall of pain the potential contributors rarely want to hurdle themselves.

same with the issues. if potential devs don't see changes, they rarely hop onto the grave to boost a project without forking it and thus stripping you off your responsibilities. (even microsoft did that with alot of repos they were interested in. just because the repos were dead. i'm talking about quite some components within visual studio code for example. xterm.js etc.)

i assume noraj is a little tired and sad of the current flood state.

yes, you want great quality prs that are easy to merge but you cannot assume the best devs on this planet will hop onto this project to help.

**Comment by noraj** [comment]
@GottZ yeah the org + project quality https://github.com/jfurrow/flood/issues/712

**Pull request closed without merging**
