### PR TITLE
Remove unused dependencies from package.json

### PR DESCRIPTION
**Pull request by bengadbois**
## Description
Removes dependencies not needed during either development or production tasks/runtime.

Unused dependencies were found using https://github.com/dylang/npm-check. It has some false positives, so I didn't accept all of them (e.g. `minami` is needed for docs but `npm-check` recommended removing given lack of runtime usage). Those packages were removed with `npm uninstall --save`.

## Related Issue
This isn't really a bug nor feature, but an optimization, which doesn't seem Issue-worthy, but I can create one if that's preferred.

## Motivation and Context
Decreases the amount of data needed during npm installing, leading to faster setup and smaller docker containers.

## How Has This Been Tested?
Ran all the commands under `Compiling assets and starting the server` and `Local Development` from the README and everything built and ran successfully without the unused dependencies now removed.

## Screenshots (if appropriate):
N/A

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by noraj** [comment]
@bengadbois This looks good, thanks for the PR. I'm asking @jfurrow to take a look at it before merging.
But why did you downgraded `feedsub` ?

**Comment by bengadbois** [comment]
Hm I didn't intentionally downgrade, I'll see if/why one of the tools did that, and if there's no good reason, update the PR. Thanks for the 👀

**Comment by bbashy** [comment]
feedsub was updated recently in https://github.com/jfurrow/flood/commit/3da1fbfc5a34212fb2955f04343af069c25bb0fe

**Comment by bengadbois** [comment]
Thanks, updated now

**Comment by jfurrow** [comment]
Sorry @bengadbois but can you please rebase?

**Comment by bengadbois** [comment]
@jfurrow rebased, should be good now

**Pull request merged**
