### PR TITLE
add nodejs LTS support in travis

### PR DESCRIPTION
**Pull request by noraj**
## Description

add nodejs LTS support in travis

## Related Issue

https://github.com/jfurrow/flood/issues/658

## Motivation and Context

We need to test on nodejs LTS.

## Types of changes

it's not a flood change.

## Checklist:

- [x] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wopian** [comment]
Testing on `7.x` should probably be dropped - it reached [end of life last summer](https://github.com/nodejs/Release#release-schedule)

**Comment by jfurrow** [comment]
@noraj I adjusted this in https://github.com/jfurrow/flood/commit/f646dd7c11e1a117d5c1aee0b86282762e1ec8d6. Let's add the `lts/*` entry (or just `10`) when Flood actually builds in Node 10.

**Comment by noraj** [comment]
@jfurrow why did you put 8 and 9 ? And not `lts/*` (LTS that is actually 8) and `node` (current that is actually 10) ? So this is lacking of node 10.

**Comment by noraj** [comment]
> lts/* or explicitly specify 10
@jfurrow I still don't understand because `lts/*`is for node 8 right now not node 10. So we can replace 8 by `lts/*` right now and wait to specify `node` or `10`  when Flood builds with Node 10.

**Comment by noraj** [comment]
> lts/* or explicitly specify 10

@jfurrow I still don't understand because `lts/*`is for node 8 right now not node 10. So we can replace 8 by `lts/*` right now and wait to specify `node` or `10` when Flood builds with Node 10.

**Comment by noraj** [comment]
@wopian I agree with you.

**Pull request merged**
