### PR TITLE
Make username case-insensitive

### LINKED ISSUE #552: Make username case-insensitive
See PR #553 

## Expected Behavior

When logging in, any variation of the case of the username should be accepted as valid.

## Current Behavior

Only the exact case is accepted.

## Possible Solution

1. Search DB in case-insensitive mode for submitted username
2. When creating users, search for existing users in case-insensitive mode

## Steps to Reproduce (for bugs)

1. Log out of Flood
2. Login with username with a different case (ex. all lowercase, uppercase)
3. Login fails.

## Context

Most applications accept any variation of the user name.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
v1.0.0
  + Commit ID (development release) `git --no-pager log -1`
```
commit 2fd0edae15d21bcb79421b6ca1b07c9ff7705bc7
Merge: aa09157 ff9efd2
Author: John Furrow <hello@johnfurrow.com>
Date:   Thu Nov 16 20:13:13 2017 -0800

    Merge pull request #539 from jfurrow/add-logout
    
    Add logout functionality
```
* Environment name and version (e.g. Chrome 39, node.js 5.4):
    Firefox 57, Node v6.12.0
* Operating System and version:
Ubuntu 17.10 Server
## Note

You may try to follow the update procedure described in the README and try again before opening this issue.

### PR DESCRIPTION
**Pull request by SanPilot**
See issue #552.

This PR makes usernames case-insensitive.

Checklist

- [x] Accept username with any case variations
- [x] Prevent creation of new users with existing usernames of any case

(Closes #552)

### CODE REVIEW

**Comment by jfurrow** [comment]
@SanPilot Why make usernames case-insensitive?

**Comment by dcousens** [comment]
IDC either way,  but, `autocapitalize="off"` would be great for that user name field.

**Comment by noraj1337** [comment]
It's better to talk about it in the issue maybe. 😄

**Comment by jfurrow** [comment]
> It's better to talk about it in the issue maybe. 😄 

I agree — thanks!

**Comment by SanPilot** [comment]
@jfurrow Yeah, sorry about that. I'm in high school, midterms are coming up. You can take over if you want, otherwise I'll complete it this weekend.

**Comment by jfurrow** [comment]
No need to apologize @SanPilot — focus on your midterms.

**Comment by SanPilot** [comment]
Ready for review!

(closes #552)

**Pull request merged**
