### PR TITLE
add node 10 (current) test support

### PR DESCRIPTION
**Pull request by noraj**
## Description

add node 10 (current) test support

## Related Issue

https://github.com/jfurrow/flood/pull/657

### CODE REVIEW

**Comment by wopian** [comment]
If we want green travis builds until 10 is actually supported (i.e when #659 is merged) you can add:

```yaml
matrix:
  fast_finish: true
  allow_failures:
  - node: 10
```

**Comment by wopian** [comment]
Sorry @noraj, it's `node_js` not `node`

**Comment by noraj** [comment]
@wopian I corrected to `node_js` in `matrix`
I paste the doc here in case we need more info: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by noraj** [comment]
@wopian This code doesn't seem to change anything in Travis build status

```
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 10
```

**Comment by noraj** [comment]
I rebased the branch on master to get the bcrypt removal commit.

**Pull request merged**
