### PR TITLE
Spanish Localization

### LINKED ISSUE #334: Spanish Localization
I'll be working on this in the next week or so.

### PR DESCRIPTION
**Pull request by nVitius**
This patch fixes #334

### CODE REVIEW

**Comment by jfurrow** [comment]
Thanks @nVitius! This looks great. The only issue I see is that we need to specify the new language in one other location: https://github.com/jfurrow/flood/blob/master/client/javascript/constants/Languages.js

**Comment by nVitius** [comment]
Okay, thanks. I've amended the commit to include that.

**Comment by jfurrow** [comment]
One last request, please run `npm run build-assets` and submit the compiled JavaScript. Then this PR is ready to merge.

**Comment by nVitius** [comment]
Ready!

**Comment by jfurrow** [comment]
Thanks so much, @nVitius!

**Comment by romancin** [comment]
Is it possible to select a language different than English by default? I want to make this change by default in a Docker image. Thank you!

**Pull request merged**
