### PR TITLE
Add Graph history duration option

### PR DESCRIPTION
**Pull request by Phr33d0m**
This pull req adds a functionality discussed in #346. A new option is available in Settings -> User Interface where the user is able to switch between the already-defined graph time functions.

image

Example of 1 week interval:
image

Please review.

PS: This is my first time touching reactjs and I hope it will be the last, although your source struct made it very easy for me so good job on that.

PS2: I accidentaly commited a change to ```server/models/history.js``` about an innecessary use of Date() inside moment(). As it's a small change I just left it be in this pullreq.

### CODE REVIEW

**Comment by jfurrow** [comment]
Thanks for this PR! I'll take a look ASAP.

**Comment by Phr33d0m** [comment]
I don't know what the ```nextEraUpdateInterval``` paremeter in the intervals is used for, so it might need to get tuned as well.

**Comment by jfurrow** [comment]
nextEraUpdateInterval represents the interval at which the next history era
receives an aggregated average rate of transfer from the shorter history
era. I am definitely open to ideas for how to make this more obvious, I
wrote this a long time ago.

I'm traveling in the carribean and have super spotty internet until next
week Wednesday. I'll try to find time to review this.

**Comment by jfurrow** [comment]
Sorry for waiting so long, but I don't think this is the right solution, and it's not your fault. The way I've written Flood's transfer history aggregation is just bad. There's no enforce consistency to the intervals and no easy way to tell when Flood just wasn't running for a given time period.

A full refactor to the history service is needed before this gets implemented in order for the displayed data to make sense.

Again, I'm sorry I've taken so long to respond to your PR. I greatly appreciate your efforts and hope you aren't completely turned off from contributing in the future.

**Comment by Phr33d0m** [comment]
@jfurrow no worries at all. I'll be using it whilest you implement a better way of doing it ;-).

**Comment by jfurrow** [comment]
Thanks for understanding @Phr33d0m! I am working on a solution right now. :)

**Comment by disrupted** [comment]
@jfurrow what's the status of this?

**Comment by jfurrow** [comment]
@disrupted The `HistoryService` still needs a full refactor for this to work properly. Not working on it right now.

**Pull request closed without merging**
